name: CI-CD
on:
  workflow_dispatch:
jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.7

    - name: Autenticação no docker hub
      uses: docker/login-action@v3.3.0
      with:
        username: ${{secrets.DOCKERHUB_USER}}
        password: ${{secrets.DOCKERHUB_PWD}}
        
    - name: Construção da imagem Docker
      uses: docker/build-push-action@v3.2.0
      with:
        context: ./src
        file: ./src/Dockerfile
        push: true
        tags:  |
          guilhermearmoa:${{github.run_number}}
          guilhermearmoa:latest
